### ISSUE TITLE
sprig workshop overhaul: current 'overview' video needs review 

### ISSUE THREAD

**Issue by karamassie** [hackclub/sprig#1074]
let's watch the intro vid and make notes (leave in comments here) on what we'd update / edit 
https://www.youtube.com/watch?v=ZOPYB6dw4Os

**Comment by LucasHT22** [comment]
The overview is perfect, I think our point is other videos with code itself, as the previous ones were:
https://youtu.be/GEbDRR_cqJI
https://youtu.be/1UTLS4aO9bQ

An overview is great, but "hands on code" is essential for learning, it shows that it's simple and that you can take risks with the code

**Comment by grymmy** [comment]
@LucasHT22 @karamassie is this issue actionable anymore, or has it been completed?  If we don't expect more movement here, please close this...

**Comment by LucasHT22** [comment]
It would be great if these new videos exists

**Comment by karamassie** [comment]
@LucasHT22 what content are we currently missing in sprig videos? I can ask ppl to make one!

**Comment by grymmy** [comment]
Based on this chatter - @karamassie, I am assigning this to you - when you do find someone who will make this, please assign the issue directly to that individual.

**Comment by karamassie** [comment]
ah, now that I dig into this more, I'm feeling with the JAMS and presentations (and in figma for editing!) and in-editor walkthrus, we are covered. closing unless we hear this is really needed. If people want materials, pls direct them to https://jams.hackclub.com/batch/sprig (and our slack for immediate help!)

**Comment by LucasHT22** [comment]
I disagree, the problem is not about having materials, is about solve the needs of those who doesn't want/parents does not allow join Slack and want to see something "hands on code" of someone really making a game, considering that our target audience is beginners, some have never used an IDE like Sprig editor. Jams are really good, but it doesn't solve this problem, doesn't even have one video "hands on code" (at least I didn't find it)

**Comment by karamassie** [comment]
okay! i'd love to see you do this!! you should know exactly where ppl are struggling
