### ISSUE TITLE
Sprig Feedback

### ISSUE THREAD

**Issue by maggie-j-liu** [hackclub/sprig#119]
Hi! The new design is super cool; I tried it out by making a [15-puzzle](https://sprig.hackclub.dev/?id=570a9d2e5595b0e1e57cbbd2b9e758d3)! Here's some feedback I have:

1. The bitmap and map editors doesn't work when there's no content between the backticks. Previously, it would throw an error, but now the editor just doesn't open: 

https://user-images.githubusercontent.com/63619830/179810858-89806f30-80e7-4579-b856-3ff996689a0e.mov

2. Map editor is so confusing because there's no grid lines... I couldn't figure out what to do after opening it for the first time, and it's also hard to count how many rows/columns there are.

3. Note and enforce that sprites can only have 1 letter name (also what happens if you run out of letters 😳?)

## Other ideas
- Would be nice if there was a built-in console for debugging, right now I just use devtools
- What's the 
  ```
  @title: 15-puzzle
  @author: maggie
  ```
  for, and are there other fields? I think an instructions field would be nice; sometimes games aren't self explanatory
- Is there a reason why we can't have permanent URLs? Would make it easier for small bugfixes and if we could customize URLs, it would be easier to share

**Comment by leomcelroy** [comment]
Wonderful feedback Maggie! Very helpful bugs to address. We broke this out into multiple issues and I think I handled each one or addressed why we won't at the moment. To review:

The codemirror extension needs a range with at least one for the text-editing through editors to work. I made it so the button doesn't appear unless that criteria is met.

You're right about the grid lines. Many people have made a similar observation so we added an indicator.

You need one character so the maps as strings system can work. I think it's unlikely one will run out of characters/numbers/symbols but it's possible.

We just tell people to use devtools. Console in the device would be more ergonomic but I think it's tough to recreate something like devtools well. Opening them up is a good skill to learn. Open to feedback on how we might improve this.

Those are metadata comments to get the name and author from the js so we can store files in javascript format (as opposed to json or something).

There is no backend, which is why the urls aren't permanent.
