### ISSUE TITLE
Parity bug on Icy_Portals 

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/sprig#1282]
**Describe the bug**
PARITY BUG. level two does not work. the portal is non-functioning on console vs on web. soft-locked as a result

**To Reproduce**
1. https://sprig.hackclub.com/gallery/Icy_Portals and load it on console
2. press a button to start game on console, then input the following button combination: dsasdsa / dsawdwdsa / sdwdsawasdw
3. Observe difference in behavior between web and console 

**Expected behavior**
snow man should teleport through the portal

**Actual behavior**  
snow man does NOT teleport through the portal

**Comment by grymmy** [comment]
@Sheepy3 Per our conversation the other day, this issue is not accepted as it does not meet the criteria for an actionable issue - this could simply be a flaw in the application's coding as opposed to an actual parity concern.  Please feel free to reopen if after investigating further one finds a specific actionable parity issue, I just do not want to get into the habit of implicitly trusting that app parity issues are platform bugs, necessarily.

**Comment by snoglobe** [comment]
this is still a problem!
