### ISSUE TITLE
Parity bug on Jumper

### ISSUE THREAD

**Issue by Sheepy3** [hackclub/sprig#1284]
**Describe the bug**
PARITY BUG. movement does not work on console, only on web editor. 

**To Reproduce**
1. https://sprig.hackclub.com/gallery/Jumper
2. run on hardware, press a key to start game, and press I to select "start"
3. Press w
4. run on web, and repeat 2/3
5. observe difference in behavior

**Expected behavior**
The player should move between the 3 rows as on the web version.

**Actual behavior**  
The player is stuck within the bottom row. 

**Screenshots**

**Comment by grymmy** [comment]
@Sheepy3 Per our conversation the other day, this issue is not accepted as it does not meet the criteria for an actionable issue - this could simply be a flaw in the application's coding as opposed to an actual parity concern.  Please feel free to reopen if after investigating further one finds a specific actionable parity issue, I just do not want to get into the habit of implicitly trusting that app parity issues are platform bugs, necessarily.
