### ISSUE TITLE
add support for arrow keys

### ISSUE THREAD

**Issue by cedric-h** [hackclub/sprig#132]

**Comment by leomcelroy** [comment]
This is a design choice, that's come up a few times. Intuitively I agree it makes sense to use the arrow keys. The reason we use w, a, s, d and i, j, k, l for the inputs is because we want the keyboard layout to map spatially to the Sprig console. Traditionally on consoles these buttons are up, down, left, right (often with a d-pad or joystick) on the left and x, y, a, b on the right for action buttons. If we want to use this convention we then have a conflict between maintaining the spatial convention or the naming convention. If we call the up, down, left, right inputs as such then it would make more sense to use the arrow keys. But if we use that naming convention then x, y, a, b seem quite arbitrary on the keyboard. 

We prioritized keeping a spatial mapping with the sprig console which is why we used w, a, s, d and i, j, k, l and then renamed those buttons/inputs accordingly.

**Comment by sampoder** [comment]
Could we map the arrow keys to WASD? And not document it but for people (like myself) who intuitively jump to arrow keys to move because we haven't played many games (I've only really ever played Minecraft seriously and changed it to using arrow keys) it would be handy to have. Personal preference, but I was playing a game of Ishan's game and this tripped me up.
