### ISSUE TITLE
Right click to delete in map and music editor

### ISSUE THREAD

**Issue by zachlatta** [hackclub/sprig#1415]
Filing this request on behalf of @Al0102.

It'd be nice if you could right click to delete in the map and music editor like you can for the bitmap editor.

**Comment by leomcelroy** [comment]
I support this.

**Comment by JosiasAurel** [comment]
Here are the relevant lines for the map editor
- https://github.com/hackclub/sprig/blob/f650372c4bdf9d23bddbc7d44517ddef078a21ce/src/components/subeditors/map-editor.tsx#L132

And for the sequncer editor 
- https://github.com/hackclub/sprig/blob/f650372c4bdf9d23bddbc7d44517ddef078a21ce/src/components/subeditors/sequencer.tsx#L82

You might want to use the leftDown/rightDown to detect left/right mouse clicks in order to toggle the cell.

**Comment by GalaxyGamingBoy** [comment]
The map editor already has right-click delete.
https://github.com/hackclub/sprig/blob/f650372c4bdf9d23bddbc7d44517ddef078a21ce/src/components/subeditors/map-editor.tsx#L133
