### ISSUE TITLE
New game button doesn't actually create a new game

### ISSUE THREAD

**Issue by recursiveforte** [hackclub/sprig#2205]
https://github.com/user-attachments/assets/5645747d-a56e-469c-8c8c-535f80627ca6

**Comment by JosiasAurel** [comment]
@recursiveforte I'm unable to reproduce this issue. 

@EerierGosling says this occurs when one is partially logged in. How do you get there?

**Comment by EerierGosling** [comment]
The issue occurs when you aren't logged in or when you have previously entered an email to have your game saved but haven't logged in (what I called 'partially logged in'). In these cases, you enter a name and then get sent to your previous game in the editor. The reason I separated these cases is because they're handled differently in the pr. Hope that helps!

**Comment by EerierGosling** [comment]
@recursiveforte could you edit this issue to add the description of the feature that fixes it?

**Comment by grymmy** [comment]
Good written description of this bug:

Title: New game button doesn’t ac….

Precondition: You are not logged in.  Go to sprig.hackclub.com
Step 1: Click buttton in middle of screen ‘Create new Game” on sprig.hackclub.com
Step 2: Click don’t save work
Step 3: Modify document
Step 4: Navigate to sprig.hackclub.com, clicking ‘i don’t care’ on popup that shows up
Step 5: Click button in middle of screen ‘Create new game”
Expect result: Content of document exactly  matches tutorial document and has proper name
Actual result: Content of document matches changes made on Step #3
