### ISSUE TITLE
mystery green pixel on start screen - sprig os

### ISSUE THREAD

**Issue by leomcelroy** [hackclub/sprig#488]
![PXL_20221102_180907899](https://user-images.githubusercontent.com/27078897/199568915-c951f157-66aa-4cef-a61b-a0eeffa7fb8a.jpg)

**Comment by cedric-h** [comment]
yep. it was bigger when we were communicating with the button polling core using the built in queue structure rather than the multicore_fifo we're using now.

if you don't launch the other core at all, it doesn't appear.

the problem is we're allocating 40kb on the stack for the screen. the other core's stack pointer -- somehow -- gets planted right in the middle of that allocation.
I have a half-rewritten renderer somewhere which would get us those 40kb back and eliminate this issue, just haven't had time to implement it yet.
