### ISSUE TITLE
Idea: Sprig project wiki

### ISSUE THREAD

**Issue by agentblack6000** [hackclub/sprig#958]
A [project wiki](https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis) for Sprig would:
1. Document the codebase, which is always helpful
2. Make it easier for new contributors to help out
3. Potentially help fix existing/new bugs (explaining code is effectively [rubber duck debugging](https://en.wikipedia.org/wiki/Rubber_duck_debugging))

**Comment by grymmy** [comment]
I have done a first cut at a [wiki](https://github.com/hackclub/sprig/wiki).  I documented a variety of things, some of which were covered in this issue.  Given the feedback in this issue was broad (not extremely specific), I am going to close this issue now.

In the future if you'd like specific copy added to the wiki, please submit a new issue.

Regards,
G
